apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: mariadb-volume-template
metadata:
  name: mariadb-volume
objects:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: mariadb-pv-claim
      namespace: ${OPENSHIFT_NAMESPACE}
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: ${STORAGE_SPACE}
      storageClassName: gp3-csi
      volumeMode: Filesystem
parameters:
  - name: OPENSHIFT_NAMESPACE
  - name: STORAGE_SPACE
