apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: mariadb-secret-template
metadata:
  name: mariadb-secret
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: mariadb
    labels:
    template: mariadb-secret-template
    annotations:
      template.openshift.io/expose-root_password: '{.data[''database-root-password'']}'
      template.openshift.io/expose-database_name: '{.data[''database-name'']}'
      template.openshift.io/expose-password: '{.data[''database-password'']}'
      template.openshift.io/expose-username: '{.data[''database-user'']}'
  stringData:
      database-root-password: ${MARIADB_ROOT_PASSWORD}
      database-name: ${MARIADB_DATABASE}
      database-password: ${MARIADB_PASSWORD}
      database-user: ${MARIADB_USER}
parameters:
- name: MARIADB_ROOT_PASSWORD
- name: MARIADB_DATABASE
- name: MARIADB_PASSWORD
- name: MARIADB_USER
